name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: checkout sources
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: setup golang
      uses: actions/setup-go@v5
      id: go
      with:
        go-version: 1.22.5

    - name: set release version env var
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: build
      run: |
        go version
        make

    - name: fix build artifacts
      run: |
        hack/make-release-binaries.sh ${{ env.RELEASE_VERSION }}

    - name: compute signature
      run: |
        hack/make-release-checksum.sh ${{ env.RELEASE_VERSION }}

    - name: create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "SHA256SUMS,httpserve-v*-linux-amd64.gz"
        token: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
